### ISSUE TITLE
1.2.3 Windows version error (access denied) + direct episode links - BOTH FIXED IN THE NEW VER

### ISSUE THREAD

**Issue by proall** [ByteDream/crunchyroll-go#11]
Not able to use the latest ver with the beta links fix.
maybe some build exe fail.

**Comment by proall** [comment]
oh, and direct episode link not working, too.

**Comment by proall** [comment]
when i'm trying to download with this link:
"https://www.crunchyroll.com/platinum-end/episode-9-the-face-of-an-assassin-819765"
not working.

but, with:
"https://www.crunchyroll.com/platinum-end"
working, but can't choose episode, its auto downloading all the season..

**Comment by ByteDream** [comment]
For me the Platinum End Ep. 9 download works fine...

... on linux ...
![image](https://user-images.githubusercontent.com/63594396/144506871-a321dc92-a930-43f0-b251-97e64e80b959.png)
... as well as on windows
![image](https://user-images.githubusercontent.com/63594396/144508234-0807c88b-bd8c-42cb-8cec-54793421cf16.

The download of your second url works as well.

And that you cannot choose the episode when passing only the anime series url is intended

**Comment by proall** [comment]
![image](https://user-images.githubusercontent.com/36814374/144509611-a9901cbb-789f-464b-bbb6-77be2a561221.png)
idk...

Also, can you please build and add the fixed 1.2.3 (win) ver to the releases?

**Comment by ByteDream** [comment]
Could you try again with the `-v` flag (`... download -v https://www.crunchyroll.com/plati...`) and paste a screenshot with the output?

I'll release the fixed version when i know why you can't download the episode. If this is an error, I don't want to make 2 new releases for one the fixed build and second the error :)

**Comment by proall** [comment]
Not working, even a non-premium episode...

**Comment by ByteDream** [comment]
Where there any extra output with the `-v` flag?

**Comment by proall** [comment]
![image](https://user-images.githubusercontent.com/36814374/144510751-813e4402-ad11-4ff8-b91a-7ab0a896e793.png)

**Comment by ByteDream** [comment]
Welllll ok, i clearly need to do more debug logs xD

[Here](https://bytedream.org/crunchy-v1.2.4_windows.exe) is the link for the fixed windows build. You may try downloading with the fixed version. Don't mind that the file is not hostet on github, i cannot attach binary in issues ¯\_(ツ)_/¯

**Comment by proall** [comment]
well, both works.
Thank you, really Appreciate your work.

btw, tried to talk about issue i had with another crunchy downloader and the developer just said: "Your win api is broken", and its not was my only problem, something like 3 pp created after me an a issue.

**Comment by ByteDream** [comment]
No problem, it's always nice to see when someone appreciates my work and says directly when an error or something other occurs :)

And I cannot understand how a dev can just say "your api is broken" and leave you alone ._.
It is his work and (in my case) I would not be able to sleep peacefully if I knew someone had a bug that I could, in theory, fix but didn't

**Comment by proall** [comment]
Well, Happy to hear there is a good man behind the screen that will support with love :)

oh, a quick question, when segment is missing or failed to download, it will try the redownload or stop with error or something?

**Comment by ByteDream** [comment]
When a segment download fails (for whatever reason) a little delay is performed and then the segment download tries to continue. If the segment could not be downloaded after 3 retries, the whole download fails

![image](https://user-images.githubusercontent.com/63594396/144513270-20302151-3e8e-49a6-b145-6629bf3740dd.png)

**Comment by proall** [comment]
oh, nice.

*lot of downloaders just skip the segment LoL*

**Comment by ByteDream** [comment]
Wow. In my experience the connection times out at least once when downloading a 1080p episode

**Comment by ByteDream** [comment]
The fixes are now released in version [v1.2.4](https://github.com/ByteDream/crunchyroll-go/releases/tag/v1.2.4)
