### ISSUE TITLE
Session ID login fails

### ISSUE THREAD

**Issue by lambdadog** [ByteDream/crunchyroll-go#15]
I found this experimenting with the API from a REST client, but I checked using `crunchy login --session-id` to ensure it wasn't my own error: It seems that `https://api.crunchyroll.com/start_session.0.json` is now returning Set-Cookie `etp_rt=deleted`. This causes the POST to `https://beta-api.crunchyroll.com/auth/v1/token` attempting to use that etp_rt cookie to fail so login fails.

**Comment by ByteDream** [comment]
Well i've tested this myself and I could not reproduce this error. The `ept_rt` cookie must contain a valid value since this is essential to login with the session id after

**Comment by lambdadog** [comment]
I also can no longer reproduce.

Bizarre.

It may have been a temporary issue or something specific to my connection to crunchyroll at the time, but I've rerun the exact same requests I was using yesterday (of course, substituting new Session IDs) and they're working now.

Closing.
