### ISSUE TITLE
Using archive ignores -d pathing

### ISSUE THREAD

**Issue by Ducksword** [ByteDream/crunchyroll-go#19]
Using crunchy-v2.0.1_windows.exe.
Path just defaults to the default download location and ignores all -d flags. 
While using all the same flags, but changing to download instead of archive, -d works as intended.

**Comment by ByteDream** [comment]
Is now fixed with [v2.0.2](https://github.com/ByteDream/crunchyroll-go/releases/tag/v2.0.2).
