### ISSUE TITLE
Naming issues

### ISSUE THREAD

**Issue by Saxy78** [ByteDream/crunchyroll-go#2]
Whenever I download something neither season no nor episode no shows. Any way to fix this?

**Comment by ByteDream** [comment]
So you want a more informative output?

Normally something like this is shown when downloading
![image](https://user-images.githubusercontent.com/63594396/130065820-ca2548fd-9e13-478d-85e4-5fd1fa6aaa37.png)

**Comment by Saxy78** [comment]
> So you want a more informative output?
> 
> Normally something like this is shown when downloading
> ![image](https://user-images.githubusercontent.com/63594396/130065820-ca2548fd-9e13-478d-85e4-5fd1fa6aaa37.png)

Yeah kinda informative , more like a simple S01E01 will help will to track the season and Episode I am doing

**Comment by ByteDream** [comment]
kk i will include this in the next update. That will probably come within the next 1 or 2 weeks. I'm currently waiting for another person who has discovered more crunchyroll api endpoints to post them so I can implement these new discoveries here

**Comment by Saxy78** [comment]
> kk i will include this in the next update. That will probably come within the next 1 or 2 weeks. I'm currently waiting for another person who has discovered more crunchyroll api endpoints to post them so I can implement these new discoveries here

Another Problem I faced is when I was trying on windows it's failing to convert to mkv or MP4 , probably due to ffmpeg binary of linux. Anyway to fix it for windows?

**Comment by ByteDream** [comment]
The ffmpeg windows binary has to be in PATH or in the same directory as the crunchy downloader

**Comment by Saxy78** [comment]
> The ffmpeg windows binary has to be in PATH or in the same directory as the crunchy downloader

Ok thanks , I will try and let you know , and great work

**Comment by kunalhazard** [comment]
![Capture](https://user-images.githubusercontent.com/25501154/130097471-4a427cbf-0b85-462e-8b44-2b57ffec3b3a.PNG)
I'm facing similar issue have already put the ffmpeg binary in PATH /same directory but didn't worked. (for some reason file path end with \ file.mkv isntead of /file.mkv).
cmd i used is [ crunchy download --audio ja-JP -o "test.mkv" https://www.crunchyroll.com/darling-in-the-franxx/episode-1-alone-and-lonesome-759575 ]

**Comment by ByteDream** [comment]
Urgh ok. 

> ![Capture](https://user-images.githubusercontent.com/25501154/130097471-4a427cbf-0b85-462e-8b44-2b57ffec3b3a.PNG)
> I'm facing similar issue have already put the ffmpeg binary in PATH /same directory but didn't worked. (for some reason file path end with /file.mkv isntead of \file.mkv).
> cmd i used is [ crunchy download --audio ja-JP -o "test.mkv" https://www.crunchyroll.com/darling-in-the-franxx/episode-1-alone-and-lonesome-759575 ]

Urgh ok. I set up a windows vm now and test it there, but this may take a while

**Comment by ByteDream** [comment]
I've created #3 for everything which is not related with the original purpose of this issue

**Comment by ByteDream** [comment]
Added in release [v1.1.0](https://github.com/ByteDream/crunchyroll-go/releases/tag/v1.1.0)
