### ISSUE TITLE
login --permanent , dont exist

### ISSUE THREAD

**Issue by Askadelion** [ByteDream/crunchyroll-go#23]
`Caching session id in separate file if only logged in permanently (with crunchy login --permanent ...) to reduce the amount of re-logging in when running multiple times.`

so it brings me the message unknown command flag or so ^^"

**Comment by IchBinLeoon** [comment]
The `--permanent` flag is actually called `--persistent`. It's a mistake in the latest release notes.

**Comment by ByteDream** [comment]
☝️ fixed the mistake in the release notes.
