### ISSUE TITLE
Windows format & output bugs

### ISSUE THREAD

**Issue by ByteDream** [ByteDream/crunchyroll-go#3]
When downloading videos under windows some bugs do appear

- Invalid success prefix (the spelling mistake is on linux too)
![image](https://user-images.githubusercontent.com/63594396/130114068-7c92c366-8270-43cb-a7fe-fc7bb5547510.png)

- Missing newline / linebreak
![image](https://user-images.githubusercontent.com/63594396/130114189-f7a497f3-21e4-45c1-9bc5-5d0b0a196dc3.png)

- Wrong destination file
![image](https://user-images.githubusercontent.com/63594396/130114311-4d7b74b1-220e-40dd-a171-23bddcb3acd7.png)

**Comment by Saxy78** [comment]
> When downloading videos under windows some bugs do appear
> 
> * Invalid success prefix (and a spelling mistake which is caused by that)
>   ![image](https://user-images.githubusercontent.com/63594396/130114068-7c92c366-8270-43cb-a7fe-fc7bb5547510.png)
> * Missing newline / linebreak
>   ![image](https://user-images.githubusercontent.com/63594396/130114189-f7a497f3-21e4-45c1-9bc5-5d0b0a196dc3.png)
> * Wrong destination file
>   ![image](https://user-images.githubusercontent.com/63594396/130114311-4d7b74b1-220e-40dd-a171-23bddcb3acd7.png)

Add ffmpeg issue on windows as well , converting from .ts to .mkv or MP4 via ffmpeg not working on windows , I tried.

**Comment by ByteDream** [comment]
It should work now fine. I've published the fixed binaries in release [1.0.1](https://github.com/ByteDream/crunchyroll-go/releases/tag/v1.0.1)
